version: "3.2"
services:
  demo:
    image: teocns/puppetask:chromium-portable
    build:
      context: ./docker/
      dockerfile: Dockerfile.chromium.portable
    platform: linux/amd64
    ports:
      - 9222:9222
      - 5999:5999
    volumes:
      - ./.chromium:/etc/puppetask/chromium/
    environment:
      LAUNCH_CMD: ./chrome --no-first-run --start-maximized --bwsi --disable-dev-shm-usage --remote-debugging-port=9223 --no-sandbox --user-data-dir
    privileged: true
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    

